### ISSUE TITLE
Uncaught node.js Error

### ISSUE THREAD

**Issue by m-vdv** [Uberi/polonium#1]
Polonium opens Facebook chat then this appears on screen:

Uncaught node.js Error 

Error: Cannot find module 'process'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:273:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at window.require (<anonymous>:4:17)
    at eval (eval at <anonymous> (file:///C:/Program%20Files/Polonium/resources/script.js:55:18), <anonymous>:47:15)
    at HTMLIFrameElement.beautify (file:///C:/Program%20Files/Polonium/resources/script.js:56:3)
    at HTMLIFrameElement.jQuery.event.dispatch (C:\Program Files\Polonium\node_modules\jquery\dist\jquery.js:4430:9)
    at HTMLIFrameElement.elemData.handle (C:\Program Files\Polonium\node_modules\jquery\dist\jquery.js:4116:28)

**Comment by m-vdv** [comment]
Not sure if it has anything to do with it but Facebook just launched: https://messenger.com/
A stand-alone Facebook messenger web-app.
